name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        sdk: [stable, master]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.sdk }}

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Run tests
        working-directory: ./example
        run: flutter test integration_test
